name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: JDK 1.11 Install
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Build
        run: |
          mvn -B clean package
          mkdir staging
          cp target/*.jar staging
        
      - name: Code Coverage (Jacoco + Coveralls)
        run: |
           mvn -B clean test jacoco:report coveralls:report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}

      - name: Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
